"use client";
import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { seedActivities, seedCustomers, seedJobs, seedNotifications, seedQuotes, seedInventoryItems, seedStores, seedMovements, seedInquiries, seedEngineeringReviews, seedSalesOrders, seedJobPlans, seedPurchaseRequests, seedPurchaseOrders, seedGoodsReceipts, seedProductionOrders, seedQcInspections, seedDeliveries, seedJobCosts, seedReworkOrders, seedCustomerComplaints, seedSalesFollowups, seedTradeOrders, seedDowntimes } from "@/data/seed";
import { Activity, Customer, Job, Notification, Quotation, Role, Status, InventoryItem, StoreLocation, StockMovement, SalesInquiry, EngineeringReview, SalesOrder, JobPlan, InquiryStatus, PurchaseRequest, PurchaseOrder, GoodsReceipt, ProductionOrder, QcInspection, DeliveryRecord, JobCost, ProductionOperation, ReworkOrder, CustomerComplaint, SalesFollowup, TradeOrder, DowntimeRecord } from "@/types";
import { canMoveJobTo } from "@/lib/permissions";
type Store = { customers: Customer[]; quotes: Quotation[]; jobs: Job[]; activities: Activity[]; notifications: Notification[]; inventoryItems: InventoryItem[]; stores: StoreLocation[]; movements: StockMovement[]; inquiries: SalesInquiry[]; engineeringReviews: EngineeringReview[]; salesOrders: SalesOrder[]; jobPlans: JobPlan[]; purchaseRequests:PurchaseRequest[]; purchaseOrders:PurchaseOrder[]; goodsReceipts:GoodsReceipt[]; productionOrders:ProductionOrder[]; qcInspections:QcInspection[]; deliveries:DeliveryRecord[]; jobCosts:JobCost[]; reworkOrders:ReworkOrder[]; customerComplaints:CustomerComplaint[]; salesFollowups:SalesFollowup[]; tradeOrders:TradeOrder[]; downtimes:DowntimeRecord[]; role: Role; addCustomer:(c:Customer)=>void; saveQuote:(q:Quotation)=>void; setQuoteStatus:(id:string,s:Status)=>void; setJobStatus:(id:string,s:Status)=>void; setInquiryStatus:(id:string,s:InquiryStatus)=>void; setReviewResult:(id:string,result:EngineeringReview["result"])=>void; createSalesOrder:(quotationId:string)=>void; approveJobPlan:(id:string)=>void; completeFollowup:(id:string,outcome:SalesFollowup["outcome"])=>void; approvePurchaseRequest:(id:string)=>void; receivePurchaseOrder:(id:string,qty:number)=>void; postStock:(itemId:string,type:StockMovement["type"],qty:number)=>void; reserveStock:(itemId:string,qty:number)=>void; transferStock:(itemId:string,toLocation:string)=>void; setOperationStatus:(orderId:string,operationId:string,status:ProductionOperation["status"])=>void; recordDowntime:(orderId:string,operationId:string)=>void; transferOperationOutput:(orderId:string,operationId:string,qty:number)=>void; recordInspection:(id:string,values:number[])=>void; createRework:(inspectionId:string)=>void; setComplaintStatus:(id:string,status:CustomerComplaint["status"])=>void; dispatchDelivery:(id:string,qty:number)=>void; dispatchTradeOrder:(id:string,qty:number)=>void; setRole:(role:Role)=>void; markRead:(id:string)=>void; markAllRead:()=>void; reset:()=>void; };
const DemoContext=createContext<Store | null>(null);
const initial={customers:seedCustomers,quotes:seedQuotes,jobs:seedJobs,activities:seedActivities,notifications:seedNotifications,inventoryItems:seedInventoryItems,stores:seedStores,movements:seedMovements,inquiries:seedInquiries,engineeringReviews:seedEngineeringReviews,salesOrders:seedSalesOrders,jobPlans:seedJobPlans,purchaseRequests:seedPurchaseRequests,purchaseOrders:seedPurchaseOrders,goodsReceipts:seedGoodsReceipts,productionOrders:seedProductionOrders,qcInspections:seedQcInspections,deliveries:seedDeliveries,jobCosts:seedJobCosts,reworkOrders:seedReworkOrders,customerComplaints:seedCustomerComplaints,salesFollowups:seedSalesFollowups,tradeOrders:seedTradeOrders,downtimes:seedDowntimes,role:"Executive" as Role};
export function DemoProvider({children}:{children:React.ReactNode}) { const [state,setState]=useState(initial); const [ready,setReady]=useState(false);
 useEffect(()=>{const saved=localStorage.getItem("ats-demo");if(saved) setState({ ...initial, ...JSON.parse(saved) });setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem("ats-demo",JSON.stringify(state))},[state,ready]);
 const store=useMemo<Store>(()=>({...state,
 addCustomer:c=>setState(s=>({...s,customers:[c,...s.customers]})),
 saveQuote:q=>setState(s=>({...s,quotes:s.quotes.some(x=>x.id===q.id)?s.quotes.map(x=>x.id===q.id?q:x):[q,...s.quotes]})),
 setQuoteStatus:(id,status)=>setState(s=>{const q=s.quotes.find(x=>x.id===id);const accepted=status==="ACCEPTED"&&q;const salesOrders=accepted&&!s.salesOrders.some(x=>x.quotationId===id)?[{id:`so-${Date.now()}`,no:`SO-${String(Date.now()).slice(-6)}`,quotationId:id,customerPoNo:"CUSTOMER-PO-PENDING",customer:q.customer,project:q.project,orderDate:"Now",requestedDelivery:q.validUntil,status:"DRAFT" as const},...s.salesOrders]:s.salesOrders;const jobs=accepted&&!s.jobs.some(j=>j.quotationId===id)?[{id:`j-${Date.now()}`,no:`JOB-${String(Date.now()).slice(-6)}`,quotationId:id,customer:q.customer,project:q.project,status:"ENGINEERING" as Status,due:"15 Oct 2026",progress:8,priority:"Normal" as const},...s.jobs]:s.jobs;return {...s,quotes:s.quotes.map(x=>x.id===id?{...x,status}:x),salesOrders,jobs,activities:[{id:`a-${Date.now()}`,at:"Now",user:"Demo User",role:s.role,action:`Quotation ${status.toLowerCase()}`,entity:q?.no??id},...s.activities]}}),
 setJobStatus:(id,status)=>setState(s=>{if(!canMoveJobTo(s.role,status))return s;return {...s,jobs:s.jobs.map(j=>j.id===id?{...j,status,progress:status==="COMPLETED"?100:Math.min(95,j.progress+15)}:j),activities:[{id:`a-${Date.now()}`,at:"Now",user:"Demo User",role:s.role,action:`Workflow moved to ${status}`,entity:s.jobs.find(j=>j.id===id)?.no??id},...s.activities]}}),
 setInquiryStatus:(id,status)=>setState(s=>({...s,inquiries:s.inquiries.map(x=>x.id===id?{...x,status}:x),activities:[{id:`a-${Date.now()}`,at:"Now",user:"Demo User",role:s.role,action:`Inquiry moved to ${status}`,entity:s.inquiries.find(x=>x.id===id)?.no??id},...s.activities]})),
 setReviewResult:(id,result)=>setState(s=>{const review=s.engineeringReviews.find(x=>x.id===id);return {...s,engineeringReviews:s.engineeringReviews.map(x=>x.id===id?{...x,result,reviewedAt:"Now"}:x),inquiries:s.inquiries.map(x=>x.id===review?.inquiryId?{...x,status:result==="FEASIBLE"?"FEASIBLE":result==="NEEDS_INFO"?"NEEDS_INFO":x.status}:x),activities:[{id:`a-${Date.now()}`,at:"Now",user:"Demo User",role:s.role,action:`Engineering review ${result.toLowerCase()}`,entity:s.inquiries.find(x=>x.id===review?.inquiryId)?.no??id},...s.activities]}}),
 createSalesOrder:quotationId=>setState(s=>{const q=s.quotes.find(x=>x.id===quotationId);if(!q||s.salesOrders.some(x=>x.quotationId===quotationId))return s;const order:SalesOrder={id:`so-${Date.now()}`,no:`SO-${String(Date.now()).slice(-6)}`,quotationId,customerPoNo:"CUSTOMER-PO-PENDING",customer:q.customer,project:q.project,orderDate:"Now",requestedDelivery:q.validUntil,status:"DRAFT"};return {...s,salesOrders:[order,...s.salesOrders],activities:[{id:`a-${Date.now()}`,at:"Now",user:"Demo User",role:s.role,action:"Sales order created",entity:order.no},...s.activities]}}),
 completeFollowup:(id,outcome)=>setState(s=>{const follow=s.salesFollowups.find(x=>x.id===id);return {...s,salesFollowups:s.salesFollowups.map(x=>x.id===id?{...x,outcome,contactedAt:"Now"}:x),quotes:s.quotes.map(x=>x.id===follow?.quotationId&&outcome==="LOST"?{...x,status:"REJECTED"}:x),activities:[{id:`a-${Date.now()}`,at:"Now",user:"Demo User",role:s.role,action:`Sales follow-up ${outcome.toLowerCase()}`,entity:s.quotes.find(x=>x.id===follow?.quotationId)?.no??id},...s.activities]}}),
 approveJobPlan:id=>setState(s=>({...s,jobPlans:s.jobPlans.map(x=>x.id===id?{...x,approvalStatus:"APPROVED"}:x),activities:[{id:`a-${Date.now()}`,at:"Now",user:"Demo User",role:s.role,action:"BOM and routing released",entity:s.jobPlans.find(x=>x.id===id)?.drawingNo??id},...s.activities]})),
 approvePurchaseRequest:id=>setState(s=>({...s,purchaseRequests:s.purchaseRequests.map(x=>x.id===id?{...x,status:"APPROVED"}:x),activities:[{id:`a-${Date.now()}`,at:"Now",user:"Demo User",role:s.role,action:"Purchase request approved",entity:s.purchaseRequests.find(x=>x.id===id)?.no??id},...s.activities]})),
 receivePurchaseOrder:(id,qty)=>setState(s=>{const po=s.purchaseOrders.find(x=>x.id===id);const pr=s.purchaseRequests.find(x=>x.id===po?.prId);const item=s.inventoryItems.find(x=>x.partNo===pr?.partNo);if(!po||qty<=0)return s;const accepted=Math.min(qty,po.qtyOrdered-po.qtyReceived);const received=po.qtyReceived+accepted;const receipt:GoodsReceipt={id:`gr-${Date.now()}`,no:`GR-${String(Date.now()).slice(-6)}`,poId:id,receivedAt:"Now",qty:accepted,acceptedQty:accepted,rejectedQty:0,warehouse:"Store 1 - Raw Materials",receivedBy:"Demo User"};return {...s,purchaseOrders:s.purchaseOrders.map(x=>x.id===id?{...x,qtyReceived:received,status:received>=x.qtyOrdered?"RECEIVED":"PARTIAL"}:x),goodsReceipts:[receipt,...s.goodsReceipts],inventoryItems:s.inventoryItems.map(x=>x.id===item?.id?{...x,currentStock:x.currentStock+accepted}:x),movements:[{id:`mv-${Date.now()}`,date:"Now",itemId:item?.id??pr?.partNo??po.id,itemName:po.item,type:"IN",qty:accepted,reference:po.no,user:"Demo User"},...s.movements],activities:[{id:`a-${Date.now()}`,at:"Now",user:"Demo User",role:s.role,action:`Goods received ${accepted} ${po.unit}`,entity:po.no},...s.activities]}}),
 postStock:(itemId,type,qty)=>setState(s=>{const item=s.inventoryItems.find(x=>x.id===itemId);if(!item||qty<=0)return s;const outbound=type==="ISSUE"||type==="OUT";const delta=outbound?-qty:qty;if(item.currentStock+delta<0)return {...s,notifications:[{id:`n-${Date.now()}`,title:"Stock transaction blocked",detail:`${item.partNo} cannot go below zero`,type:"INVENTORY",read:false},...s.notifications]};return {...s,inventoryItems:s.inventoryItems.map(x=>x.id===itemId?{...x,currentStock:x.currentStock+delta,reservedStock:outbound?Math.max(0,(x.reservedStock??0)-qty):x.reservedStock}:x),movements:[{id:`mv-${Date.now()}`,date:"Now",itemId,itemName:item.name,type,qty:delta,reference:type==="ISSUE"?"WO-2026-00128":"STOCK-ACTION",user:"Demo User",lotNo:item.lotNo},...s.movements],activities:[{id:`a-${Date.now()}`,at:"Now",user:"Demo User",role:s.role,action:`Stock ${type.toLowerCase()} ${qty} ${item.unit}`,entity:item.partNo},...s.activities]}}),
 reserveStock:(itemId,qty)=>setState(s=>({...s,inventoryItems:s.inventoryItems.map(x=>x.id===itemId?{...x,reservedStock:Math.min(x.currentStock,(x.reservedStock??0)+Math.max(0,qty))}:x)})),
 transferStock:(itemId,toLocation)=>setState(s=>{const item=s.inventoryItems.find(x=>x.id===itemId);if(!item)return s;return {...s,inventoryItems:s.inventoryItems.map(x=>x.id===itemId?{...x,location:toLocation}:x),movements:[{id:`mv-${Date.now()}`,date:"Now",itemId,itemName:item.name,type:"TRANSFER",qty:item.currentStock,reference:"STORE-TRANSFER",user:"Demo User",lotNo:item.lotNo,fromLocation:item.location,toLocation},...s.movements]}}),
 setOperationStatus:(orderId,operationId,status)=>setState(s=>({...s,productionOrders:s.productionOrders.map(order=>order.id===orderId?{...order,status:status==="COMPLETED"?order.status:"IN_PROGRESS",operations:order.operations.map(op=>op.id===operationId?{...op,status,actualStart:status==="IN_PROGRESS"?(op.actualStart??"Now"):op.actualStart,actualFinish:status==="COMPLETED"?"Now":op.actualFinish}:op)}:order),activities:[{id:`a-${Date.now()}`,at:"Now",user:"Demo User",role:s.role,action:`Operation ${status.toLowerCase()}`,entity:s.productionOrders.find(x=>x.id===orderId)?.no??orderId},...s.activities]})),
 recordDowntime:(orderId,operationId)=>setState(s=>{const record:DowntimeRecord={id:`dt-${Date.now()}`,productionOrderId:orderId,operationId,reason:"Machine setup / unplanned stop",startedAt:"Now",endedAt:"Now + 15 min",minutes:15,recordedBy:"Demo User"};return {...s,downtimes:[record,...s.downtimes],activities:[{id:`a-${Date.now()}`,at:"Now",user:"Demo User",role:s.role,action:"Downtime recorded (15 min)",entity:s.productionOrders.find(x=>x.id===orderId)?.no??orderId},...s.activities]}}),
 transferOperationOutput:(orderId,operationId,qty)=>setState(s=>({...s,productionOrders:s.productionOrders.map(order=>order.id===orderId?{...order,operations:order.operations.map((op,index,all)=>{if(op.id!==operationId)return op;const next=all[index+1];if(!next)return op;return {...op,qtyGood:Math.max(op.qtyGood,qty)};})}:order),activities:[{id:`a-${Date.now()}`,at:"Now",user:"Demo User",role:s.role,action:`Partial output transferred ${qty} PCS`,entity:s.productionOrders.find(x=>x.id===orderId)?.no??orderId},...s.activities]})),
 recordInspection:(id,values)=>setState(s=>{const source=s.qcInspections.find(x=>x.id===id);if(!source)return s;const measurements=source.measurements.map((m,index)=>{const measured=values[index];return {...m,measured,result:measured>=m.lowerLimit&&measured<=m.upperLimit?"PASS" as const:"FAIL" as const}});const failed=measurements.some(x=>x.result==="FAIL");return {...s,qcInspections:s.qcInspections.map(x=>x.id===id?{...x,measurements,status:failed?"FAIL":"PASS"}:x),notifications:failed?[{id:`n-${Date.now()}`,title:"QC measurement failed",detail:`${source.no} requires disposition`,type:"QC",read:false},...s.notifications]:s.notifications,activities:[{id:`a-${Date.now()}`,at:"Now",user:"Demo User",role:s.role,action:failed?"QC failed — rework required":"QC inspection passed",entity:source.no},...s.activities]}}),
 createRework:inspectionId=>setState(s=>{const inspection=s.qcInspections.find(x=>x.id===inspectionId);if(!inspection||s.reworkOrders.some(x=>x.inspectionId===inspectionId))return s;const order:ReworkOrder={id:`rw-${Date.now()}`,no:`RW-${String(Date.now()).slice(-6)}`,inspectionId,productionOrderId:inspection.productionOrderId,operationId:inspection.operationId,quantity:1,reason:"Measurement outside tolerance",status:"OPEN"};return {...s,reworkOrders:[order,...s.reworkOrders],qcInspections:s.qcInspections.map(x=>x.id===inspectionId?{...x,status:"REWORK"}:x),activities:[{id:`a-${Date.now()}`,at:"Now",user:"Demo User",role:s.role,action:"Rework order created",entity:order.no},...s.activities]}}),
 setComplaintStatus:(id,status)=>setState(s=>({...s,customerComplaints:s.customerComplaints.map(x=>x.id===id?{...x,status}:x),activities:[{id:`a-${Date.now()}`,at:"Now",user:"Demo User",role:s.role,action:`Customer complaint ${status.toLowerCase()}`,entity:s.customerComplaints.find(x=>x.id===id)?.no??id},...s.activities]})),
 dispatchDelivery:(id,qty)=>setState(s=>{const delivery=s.deliveries.find(x=>x.id===id);if(!delivery||qty<=0)return s;const delivered=Math.min(delivery.packedQty,delivery.deliveredQty+qty);return {...s,deliveries:s.deliveries.map(x=>x.id===id?{...x,deliveredQty:delivered,status:delivered>=x.packedQty?"DELIVERED":"PARTIAL",recipient:"Customer Receiving"}:x),jobs:s.jobs.map(x=>x.id===delivery.jobId&&delivered>=delivery.packedQty?{...x,status:"DELIVERED",progress:100}:x),activities:[{id:`a-${Date.now()}`,at:"Now",user:"Demo User",role:s.role,action:`Delivery dispatched ${qty} PCS`,entity:delivery.no},...s.activities]}}),
 dispatchTradeOrder:(id,qty)=>setState(s=>{const order=s.tradeOrders.find(x=>x.id===id);const item=s.inventoryItems.find(x=>x.id===order?.itemId);if(!order||!item||qty<=0||item.currentStock<qty)return s;const delivered=Math.min(order.quantity,order.deliveredQty+qty);return {...s,tradeOrders:s.tradeOrders.map(x=>x.id===id?{...x,deliveredQty:delivered,status:delivered>=x.quantity?"DELIVERED":"PARTIAL"}:x),inventoryItems:s.inventoryItems.map(x=>x.id===item.id?{...x,currentStock:x.currentStock-qty}:x),movements:[{id:`mv-${Date.now()}`,date:"Now",itemId:item.id,itemName:item.name,type:"OUT",qty:-qty,reference:order.no,user:"Demo User",lotNo:item.lotNo},...s.movements]}}),
 setRole:role=>setState(s=>({...s,role})), markRead:id=>setState(s=>({...s,notifications:s.notifications.map(n=>n.id===id?{...n,read:true}:n)})),markAllRead:()=>setState(s=>({...s,notifications:s.notifications.map(n=>({...n,read:true}))})),reset:()=>setState(initial)}),[state]);
 return <DemoContext.Provider value={store}>{children}</DemoContext.Provider> }
export const useDemo=()=>{const v=useContext(DemoContext);if(!v)throw new Error("DemoProvider missing");return v};
